before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libxml2-utils

script:
    - xmllint --schema http://www.w3.org/2001/XMLSchema.xsd --noout xsd/extension/*.xsd
    - xmllint --schema xsd/extension/*.xsd --noout iep-samples/*.xml
    - xmllint --schema http://tools.niem.gov/IEPD/mpd-catalog-3.0.xsd --noout mpd-catalog.xml
